import fs from 'node:fs';
import vm from 'node:vm';

const context={};
vm.createContext(context);
vm.runInContext(fs.readFileSync('logic.js','utf8'),context);
const logic=context.CBT_LOGIC;
const q={id:'PAST-TEST',answer:[2],subject:'소프트웨어 설계',unit:'기출문제'};
let row=logic.updateWrongRecord(null,q,[1],false,'2026-08-21T00:00:00Z');
if(row.wrongCount!==1||!row.active)throw new Error('first wrong');
row=logic.updateWrongRecord(row,q,[2],false,'2026-08-21T00:01:00Z');
if(row.wrongCount!==2||row.history.length!==2)throw new Error('repeat wrong');
row=logic.updateWrongRecord(row,q,q.answer,true,'2026-08-21T00:02:00Z');
if(row.active||row.wrongCount!==2||row.history.length!==3)throw new Error('correct review');
if(logic.updateWrongRecord(null,q,q.answer,true,'2026-08-21T00:03:00Z')!==null)throw new Error('correct-only record');
if(fs.existsSync('bank.js')||fs.existsSync('question-bank.json'))throw new Error('public question data must not exist');
const html=fs.readFileSync('index.html','utf8');
if(!html.includes('private-pack-input')||!html.includes('drive-connect')||html.includes('bank.js'))throw new Error('private pack importer and Drive sync UI');
const app=fs.readFileSync('app.js','utf8');
if(!app.includes("jeongbo-private-pack-v2")||!app.includes('questions.length!==1800')||!app.includes('sets.size!==18'))throw new Error('2020-2025 pack validation');
if(!app.includes('confidences')||!app.includes('취약 개념 TOP10')&&!fs.readFileSync('index.html','utf8').includes('취약 개념 TOP10'))throw new Error('confidence and weak concept analysis');
const concepts=fs.readFileSync('concept-engine.js','utf8');
if(!concepts.includes('CBT_CONCEPTS')||!concepts.includes('slice(-6)'))throw new Error('concept analysis engine');
const drive=fs.readFileSync('drive-sync.js','utf8');
if(!drive.includes('https://www.googleapis.com/auth/drive.appdata')||!drive.includes("parents:['appDataFolder']"))throw new Error('private Drive appDataFolder sync');
if(/client_secret/i.test(drive))throw new Error('client secret must not be published');
const privacy=fs.readFileSync('privacy.html','utf8');
if(!privacy.includes('drive.appdata')||!privacy.includes('별도의 운영 서버로 개인정보를 수집하거나 전송하지 않습니다'))throw new Error('privacy disclosure');
console.log(JSON.stringify({publicQuestions:0,wrongCount:row.wrongCount,active:row.active,history:row.history.length,driveScope:'appdata'}));
